#ifndef CPU_FEATURES_DOTNET_CPU_TYPE_AARCH64_H
#define CPU_FEATURES_DOTNET_CPU_TYPE_AARCH64_H

#include "cpureg_aarch64.h"
#include <stddef.h>
#include <stdint.h>

CPU_FEATURES_DOTNET_START_CPP_NAMESPACE

#define MPIDR_UP_BITMASK	  (0x1 << 30)
#define MPIDR_MT_BITMASK	  (0x1 << 24)
#define MPIDR_HWID_BITMASK	UL(0xFF00FFFFFF)

#define MPIDR_LEVEL_BITS_SHIFT	3
#define MPIDR_LEVEL_BITS	      (1 << MPIDR_LEVEL_BITS_SHIFT)
#define MPIDR_LEVEL_MASK	      ((1 << MPIDR_LEVEL_BITS) - 1)

#define MPIDR_LEVEL_SHIFT(level) \
	(((1 << level) >> 1) << MPIDR_LEVEL_BITS_SHIFT)

#define MPIDR_AFFINITY_LEVEL(mpidr, level) \
	((mpidr >> MPIDR_LEVEL_SHIFT(level)) & MPIDR_LEVEL_MASK)

#define MIDR_REVISION_MASK	0xF
#define MIDR_REVISION(midr)	((midr) & MIDR_REVISION_MASK)
#define MIDR_PARTNUM_SHIFT	4
#define MIDR_PARTNUM_MASK	  (0xFFF << MIDR_PARTNUM_SHIFT)
#define MIDR_PARTNUM(midr)	\
	(((midr) & MIDR_PARTNUM_MASK) >> MIDR_PARTNUM_SHIFT)
#define MIDR_ARCHITECTURE_SHIFT	16
#define MIDR_ARCHITECTURE_MASK	(0xF << MIDR_ARCHITECTURE_SHIFT)
#define MIDR_ARCHITECTURE(midr)	\
	(((midr) & MIDR_ARCHITECTURE_MASK) >> MIDR_ARCHITECTURE_SHIFT)
#define MIDR_VARIANT_SHIFT	20
#define MIDR_VARIANT_MASK	  (0xF << MIDR_VARIANT_SHIFT)
#define MIDR_VARIANT(midr)	\
	(((midr) & MIDR_VARIANT_MASK) >> MIDR_VARIANT_SHIFT)
#define MIDR_IMPLEMENTOR_SHIFT	24
#define MIDR_IMPLEMENTOR_MASK	(0xFF << MIDR_IMPLEMENTOR_SHIFT)
#define MIDR_IMPLEMENTOR(midr)	\
	(((midr) & MIDR_IMPLEMENTOR_MASK) >> MIDR_IMPLEMENTOR_SHIFT)

#define MIDR_CPU_MODEL(imp, partnum) \
	(((imp)			<< MIDR_IMPLEMENTOR_SHIFT) | \
	(0xf			<< MIDR_ARCHITECTURE_SHIFT) | \
	((partnum)		<< MIDR_PARTNUM_SHIFT))

#define MIDR_CPU_VAR_REV(var, rev) \
	(((var)	<< MIDR_VARIANT_SHIFT) | (rev))

#define MIDR_CPU_MODEL_MASK (MIDR_IMPLEMENTOR_MASK | MIDR_PARTNUM_MASK | \
			     MIDR_ARCHITECTURE_MASK)

#define ARM_CPU_IMP_ARM			          0x41
#define ARM_CPU_IMP_APM			          0x50
#define ARM_CPU_IMP_CAVIUM		        0x43
#define ARM_CPU_IMP_BRCM		          0x42
#define ARM_CPU_IMP_QCOM		          0x51
#define ARM_CPU_IMP_NVIDIA		        0x4E
#define ARM_CPU_IMP_FUJITSU		        0x46
#define ARM_CPU_IMP_HISI		          0x48
#define ARM_CPU_IMP_APPLE		          0x61

#define ARM_CPU_PART_AEM_V8		        0xD0F
#define ARM_CPU_PART_FOUNDATION		    0xD00
#define ARM_CPU_PART_CORTEX_A57		    0xD07
#define ARM_CPU_PART_CORTEX_A72		    0xD08
#define ARM_CPU_PART_CORTEX_A53		    0xD03
#define ARM_CPU_PART_CORTEX_A73		    0xD09
#define ARM_CPU_PART_CORTEX_A75		    0xD0A
#define ARM_CPU_PART_CORTEX_A35		    0xD04
#define ARM_CPU_PART_CORTEX_A55		    0xD05
#define ARM_CPU_PART_CORTEX_A76		    0xD0B
#define ARM_CPU_PART_NEOVERSE_N1	    0xD0C
#define ARM_CPU_PART_CORTEX_A77		    0xD0D

#define APM_CPU_PART_POTENZA		      0x000

#define CAVIUM_CPU_PART_THUNDERX	    0x0A1
#define CAVIUM_CPU_PART_THUNDERX_81XX	0x0A2
#define CAVIUM_CPU_PART_THUNDERX_83XX	0x0A3
#define CAVIUM_CPU_PART_THUNDERX2	    0x0AF

#define BRCM_CPU_PART_BRAHMA_B53	    0x100
#define BRCM_CPU_PART_VULCAN		      0x516

#define QCOM_CPU_PART_FALKOR_V1		    0x800
#define QCOM_CPU_PART_FALKOR		      0xC00
#define QCOM_CPU_PART_KRYO		        0x200
#define QCOM_CPU_PART_KRYO_2XX_GOLD	  0x800
#define QCOM_CPU_PART_KRYO_2XX_SILVER	0x801
#define QCOM_CPU_PART_KRYO_3XX_SILVER	0x803
#define QCOM_CPU_PART_KRYO_4XX_GOLD	  0x804
#define QCOM_CPU_PART_KRYO_4XX_SILVER	0x805

#define NVIDIA_CPU_PART_DENVER		    0x003
#define NVIDIA_CPU_PART_CARMEL		    0x004

#define FUJITSU_CPU_PART_A64FX		    0x001

#define HISI_CPU_PART_TSV110		      0xD01

#define APPLE_CPU_PART_M1_ICESTORM	  0x022
#define APPLE_CPU_PART_M1_FIRESTORM	  0x023

#define MIDR_CORTEX_A53             MIDR_CPU_MODEL(ARM_CPU_IMP_ARM, ARM_CPU_PART_CORTEX_A53)
#define MIDR_CORTEX_A57             MIDR_CPU_MODEL(ARM_CPU_IMP_ARM, ARM_CPU_PART_CORTEX_A57)
#define MIDR_CORTEX_A72             MIDR_CPU_MODEL(ARM_CPU_IMP_ARM, ARM_CPU_PART_CORTEX_A72)
#define MIDR_CORTEX_A73             MIDR_CPU_MODEL(ARM_CPU_IMP_ARM, ARM_CPU_PART_CORTEX_A73)
#define MIDR_CORTEX_A75             MIDR_CPU_MODEL(ARM_CPU_IMP_ARM, ARM_CPU_PART_CORTEX_A75)
#define MIDR_CORTEX_A35             MIDR_CPU_MODEL(ARM_CPU_IMP_ARM, ARM_CPU_PART_CORTEX_A35)
#define MIDR_CORTEX_A55             MIDR_CPU_MODEL(ARM_CPU_IMP_ARM, ARM_CPU_PART_CORTEX_A55)
#define MIDR_CORTEX_A76	            MIDR_CPU_MODEL(ARM_CPU_IMP_ARM, ARM_CPU_PART_CORTEX_A76)
#define MIDR_CORTEX_A77	            MIDR_CPU_MODEL(ARM_CPU_IMP_ARM, ARM_CPU_PART_CORTEX_A77)

#define MIDR_NEOVERSE_N1            MIDR_CPU_MODEL(ARM_CPU_IMP_ARM, ARM_CPU_PART_NEOVERSE_N1)

#define MIDR_THUNDERX	              MIDR_CPU_MODEL(ARM_CPU_IMP_CAVIUM, CAVIUM_CPU_PART_THUNDERX)
#define MIDR_THUNDERX_81XX          MIDR_CPU_MODEL(ARM_CPU_IMP_CAVIUM, CAVIUM_CPU_PART_THUNDERX_81XX)
#define MIDR_THUNDERX_83XX          MIDR_CPU_MODEL(ARM_CPU_IMP_CAVIUM, CAVIUM_CPU_PART_THUNDERX_83XX)
#define MIDR_CAVIUM_THUNDERX2       MIDR_CPU_MODEL(ARM_CPU_IMP_CAVIUM, CAVIUM_CPU_PART_THUNDERX2)

#define MIDR_BRAHMA_B53             MIDR_CPU_MODEL(ARM_CPU_IMP_BRCM, BRCM_CPU_PART_BRAHMA_B53)
#define MIDR_BRCM_VULCAN            MIDR_CPU_MODEL(ARM_CPU_IMP_BRCM, BRCM_CPU_PART_VULCAN)

#define MIDR_QCOM_FALKOR_V1         MIDR_CPU_MODEL(ARM_CPU_IMP_QCOM, QCOM_CPU_PART_FALKOR_V1)
#define MIDR_QCOM_FALKOR            MIDR_CPU_MODEL(ARM_CPU_IMP_QCOM, QCOM_CPU_PART_FALKOR)
#define MIDR_QCOM_KRYO              MIDR_CPU_MODEL(ARM_CPU_IMP_QCOM, QCOM_CPU_PART_KRYO)
#define MIDR_QCOM_KRYO_2XX_GOLD     MIDR_CPU_MODEL(ARM_CPU_IMP_QCOM, QCOM_CPU_PART_KRYO_2XX_GOLD)
#define MIDR_QCOM_KRYO_2XX_SILVER   MIDR_CPU_MODEL(ARM_CPU_IMP_QCOM, QCOM_CPU_PART_KRYO_2XX_SILVER)
#define MIDR_QCOM_KRYO_3XX_SILVER   MIDR_CPU_MODEL(ARM_CPU_IMP_QCOM, QCOM_CPU_PART_KRYO_3XX_SILVER)
#define MIDR_QCOM_KRYO_4XX_GOLD     MIDR_CPU_MODEL(ARM_CPU_IMP_QCOM, QCOM_CPU_PART_KRYO_4XX_GOLD)
#define MIDR_QCOM_KRYO_4XX_SILVER   MIDR_CPU_MODEL(ARM_CPU_IMP_QCOM, QCOM_CPU_PART_KRYO_4XX_SILVER)

#define MIDR_NVIDIA_DENVER          MIDR_CPU_MODEL(ARM_CPU_IMP_NVIDIA, NVIDIA_CPU_PART_DENVER)
#define MIDR_NVIDIA_CARMEL          MIDR_CPU_MODEL(ARM_CPU_IMP_NVIDIA, NVIDIA_CPU_PART_CARMEL)

#define MIDR_FUJITSU_A64FX          MIDR_CPU_MODEL(ARM_CPU_IMP_FUJITSU, FUJITSU_CPU_PART_A64FX)

#define MIDR_HISI_TSV110            MIDR_CPU_MODEL(ARM_CPU_IMP_HISI, HISI_CPU_PART_TSV110)

#define MIDR_APPLE_M1_ICESTORM      MIDR_CPU_MODEL(ARM_CPU_IMP_APPLE, APPLE_CPU_PART_M1_ICESTORM)
#define MIDR_APPLE_M1_FIRESTORM     MIDR_CPU_MODEL(ARM_CPU_IMP_APPLE, APPLE_CPU_PART_M1_FIRESTORM)

typedef enum {
    UNKNOWN_IMPL_AARCH64,
    ARM,
    APM,
    CAVIUM,
    BRCM,
    QCOM,
    NVIDIA,
    FUJITSU,
    HISI,
    APPLE
} aarch64_impl;

typedef enum {
  UNKNOWN_PART_NUM_AARCH64,
  AEM_V8,
  FOUNDATION,
  CORTEX_A35,
  CORTEX_A53,
  CORTEX_A55,
  CORTEX_A57,
  CORTEX_A72,
  CORTEX_A73,
  CORTEX_A75,
  CORTEX_A76,
  CORTEX_A77,
  NEOVERSE_N1,
  POTENZA,
  THUNDERX,
  THUNDERX_81XX,
  THUNDERX_83XX,
  THUNDERX2,
  BRAHMA_B53,
  VULCAN,
  FALKOR_V1,
  FALKOR,
  KRYO,
  KRYO_2XX_GOLD,
  KRYO_2XX_SILVER,
  KRYO_3XX_SILVER,
  KRYO_4XX_GOLD,
  KRYO_4XX_SILVER,
  DENVER,
  CARMEL,
  A64FX,
  TSV110,
  M1_ICESTORM,
  M1_FIRESTORM
} aarch64_part_num;

CPU_FEATURES_DOTNET_DLL_EXPORT uint64_t __read_cpuid_id(void);
CPU_FEATURES_DOTNET_DLL_EXPORT uint64_t __read_cpuid_mpidr(void);
CPU_FEATURES_DOTNET_DLL_EXPORT uint64_t __read_cpuid_implementor(void);
CPU_FEATURES_DOTNET_DLL_EXPORT uint64_t __read_cpuid_part_number(void);
CPU_FEATURES_DOTNET_DLL_EXPORT uint64_t __read_cpuid_cachetype(void);

CPU_FEATURES_DOTNET_DLL_EXPORT aarch64_impl get_aarch64_impl(void);
CPU_FEATURES_DOTNET_DLL_EXPORT aarch64_part_num get_aarch64_part_num(void);

CPU_FEATURES_DOTNET_END_CPP_NAMESPACE

#endif //CPU_FEATURES_DOTNET_CPU_TYPE_AARCH64_H
