kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: arm32v7
  image: toor1245/cpu_features-dotnet:manifest-arm32v7
  commands:
    - apt-get update && apt-get -y install cmake
    - cmake --version
    - cmake -S. -Bcmake-build-debug -DCMAKE_BUILD_TYPE=Debug
    - cmake --build cmake-build-debug --target all
    - dotnet build
    - dotnet test "tests"

trigger:
  branch:
    - master
  event:
    - pull_request