kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: arm32v7
  image: toor1245/dotnet/sdk:5.0-buster-slim-arm32v7
  commands:
    - apt-get update && apt-get -y install cmake
    - cmake --version
    - cmake -S. -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release
    - cmake --build cmake-build-release --target all
    - dotnet build -c Release --force
    - dotnet test "tests/CpuFeaturesDotNet.UnitTesting.dll" -c Release -v=normal --runtime linux-arm --force

trigger:
  branch:
    - master
  event:
    - pull_request