kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: arm32v7
  image: toor1245/cpu_features-dotnet:manifest-arm32v7
  commands:
    - ls
    - apt-get update && apt-get -y install cmake
    - cmake --version
    - cmake -S. -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release
    - cmake --build cmake-build-release --target all
    - arch
    - dotnet build
    - dotnet test

trigger:
  branch:
    - master
  event:
    - pull_request