kind: pipeline
type: docker
name: default

platform:
  os: linux
  dist: 
  arch: arm

steps:
- name: arm32v7
  image: toor1245/cpu_features-dotnet:manifest-arm32v7
  commands:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker run -i --rm toor1245/cpu_features-dotnet:manifest-arm32v7 /bin/bash -c "dotnet build && dotnet test CpuFeaturesDotNet.UnitTesting.dll"
