kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: arm32v7
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm32v7
  commands:
    - ls
    - apt-get update && apt-get -y install cmake
    - cmake --version
    - cmake -S. -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release
    - cmake --build cmake-build-release --target all
    - cd src
    - cd CpuFeaturesDotNet
    - cd Native
    - cd Platforms
    - cd linux
    - cd aarch32
    - ls
    - arch
    #- dotnet build -c Release --force
    #- dotnet test "tests" -c Release -v=normal

trigger:
  branch:
    - master
  event:
    - pull_request