kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: arm32v7
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm32v7
  commands:
    - apt-get update && apt-get -y install cmake
    - cmake --version
    - cmake -S. -Bcmake-build-debug -DCMAKE_BUILD_TYPE=Debug
    - cmake --build cmake-build-debug --target all
    - dotnet build --force
    - dotnet test
    - cd /drone/src/tests/bin/Debug/net5.0/Native/Platforms/linux/aarch32
    - ls

trigger:
  branch:
    - master
  event:
    - pull_request