kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: arm32v7
  commands:
    - dotnet build
    - dotnet test

trigger:
  branch:
    - master
  event:
    - pull_request