kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: arm32v7
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm32v7
  commands:
    - ls
    - apt-get update && apt-get -y install cmake
    - cmake --version
    - cmake -S. -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release
    - cmake --build cmake-build-release --target all
    - dotnet build -c Release --force
    - cd tests
    - dotnet publish -c Release --runtime linux-arm
    - apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    - echo "deb [arch=armhf signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt-get install docker-ce docker-ce-cli containerd.io
    - apt-cache madison docker-ce
    #- apt-get install docker-ce=<VERSION_STRING> docker-ce-cli=<VERSION_STRING> containerd.io
    #- docker build -t toor1245/cpu_features-dotnet:manifest-arm32v7 -f ./Dockerfile.buster-slim-arm32v7 .
    #- docker run --rm --privileged multiarch/qemu-user-static:register --reset
    #- docker run -i --rm toor1245/cpu_features-dotnet:manifest-arm32v7

trigger:
  branch:
    - master
  event:
    - pull_request