kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: arm32v7
  image: toor1245/cpu_features-dotnet:armhf
  commands:
    - ls
    - dotnet build
    - dotnet test


trigger:
  branch:
    - master
  event:
    - pull_request