language: csharp
solution: CpuFeaturesDotNet.sln

mono: none

dotnet: 5.0.102

before_install:
  - sudo apt-get update
  - sudo apt install nuget

install:
  - nuget restore CpuFeaturesDotNet.sln

matrix:
  # Toolchains for little-endian, hard-float, 32-bit ARMv7 (and earlier) for GNU/Linux systems
  - arch: arm64 
  - os: linux
    env:
      TOOLCHAIN=LINARO
      TARGET=arm-linux-gnueabihf
      QEMU_ARCH=arm
  # Toolchains for little-endian, 32-bit ARMv8 for GNU/Linux systems
  - arch: arm64 
  - os: linux
    env:
      TOOLCHAIN=LINARO
      TARGET=armv8l-linux-gnueabihf
      QEMU_ARCH=arm
  # Toolchains for little-endian, soft-float, 32-bit ARMv7 (and earlier) for GNU/Linux systems
  - arch: arm64 
  - os: linux
    env:
      TOOLCHAIN=LINARO
      TARGET=arm-linux-gnueabi
      QEMU_ARCH=arm
      
script:
  - dotnet --version
  - dotnet build "src/CpuFeaturesDotNet" -c Release --force
  - dotnet test "tests" -c Release --runtime linux-arm
