language: csharp
solution: CpuFeaturesDotNet.sln

cache:
  timeout: 1000
  directories:
    - $HOME/cpu_features_dotnet_archives

mono: none

dotnet: 5.0.102

before_install:
  - sudo apt-get update
  - sudo apt install nuget

install:
  - nuget restore CpuFeaturesDotNet.sln

matrix:
  # Toolchains for little-endian, hard-float, 32-bit ARMv7 (and earlier) for GNU/Linux systems
  - os: linux
    arch: arm64
      
script:
  - bash -e -x ./scripts/run_integration.sh
