language: csharp
mono: none

dotnet: 5.0

matrix:
  include:
    - os: linux
sudo: required
services:
  - docker

after_success: |
  sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  sudo docker run -i --rm toor1245/cpu_features-dotnet:manifest-arm32v7 /bin/bash -c "dotnet build && dotnet test CpuFeaturesDotNet.UnitTesting.dll"
