language: csharp
solution: CpuFeaturesDotNet.sln

#cache:
#  timeout: 1000
#  directories:
#    - $HOME/cpu_features_dotnet_archives

#mono: none

dotnet: 5.0

services:
  - docker

before_install:
- sudo apt-get update
- sudo apt install nuget
- sudo docker pull toor1245/cpu_features-dotnet:arm32v7
- 

#install:
#  - nuget restore CpuFeaturesDotNet.sln

matrix:
  # Toolchains for little-endian, hard-float, 32-bit ARMv7 (and earlier) for GNU/Linux systems
  - os: linux
    arch: arm64
      
script:
  - sudo docker run -it --rm oor1245/cpu_features-dotnet:arm32v7 /bin/sh -c "dotnet test CpuFeaturesDotNet.UnitTesting.dll"
