#ifndef CPU_FEATURES_DOTNET_STRING_UTILS_H
#define CPU_FEATURES_DOTNET_STRING_UTILS_H

#include "cpu_features_macros.h"
#include <string.h>

CPU_FEATURES_DOTNET_START_CPP_NAMESPACE

CPU_FEATURES_DOTNET_DLL_EXPORT size_t _strlen(const char* str);

CPU_FEATURES_DOTNET_END_CPP_NAMESPACE

#endif // CPU_FEATURES_DOTNET_STRING_UTILS_H
