FROM multiarch/debian-debootstrap:arm64-buster-slim
RUN apt-get update && apt-get install -y curl gnupg icu-devtools
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm64v8
COPY bin/Release/net5.0/linux-arm64/publish/ App/
RUN uname -a
WORKDIR /App
ENTRYPOINT ["dotnet", "test", "CpuFeaturesDotNet.UnitTesting.dll", "-v=normal"]