FROM multiarch/debian-debootstrap:armhf-buster-slim
RUN apt-get update && apt-get install -y curl gnupg icu-devtools
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm32v7
COPY bin/Release/net5.0/linux-arm/publish/ UnitTesting/
WORKDIR /UnitTesting
ENTRYPOINT ["dotnet", "test", "CpuFeaturesDotNet.UnitTesting.dll", "-v=normal"]
