name: Run Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    runs-on: ${{ cpu.config.os }}
    strategy:
      matrix:
        config:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
          
    name: Run unit tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core 3.1 @ Latest
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'

      - name: Setup .NET 5.0 @ Latest
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Create build
        run: dotnet build "src" -c Release --force

      - name: Run Unit Tests
        run: dotnet test "tests/CpuFeaturesDotNet.UnitTesting" -c Release

  lint:
    runs-on: ubuntu-latest
    name: Code Convention Check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1.7.2

      - name: Setup dotnet-format tool
        run: dotnet tool install --global dotnet-format --version 4.1.131201

      - name: Check MatrixDotNet
        run: dotnet format "src/CpuFeaturesDotNet.csproj" --check --verbosity diagnostic
