name: run dotnet tests(Linux ARM)
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  arm32v7:
    runs-on: [self-hosted, linux, ARM]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Qemu
        run: |
          sudo apt-get update
          sudo snap install qemu-virgil --classic
      
      - name: Run Unit Tests
        run: |
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo docker run --platform "linux/arm/v7" -i --rm toor1245/cpu_features-dotnet:manifest-arm32v7 /bin/bash -c "dotnet build && dotnet test CpuFeaturesDotNet.UnitTesting.dll"
