name: Create Nuget Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: toor1245/cpu-features-dotnet-storage

      - name: Set git credentials
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create branch
        run: git checkout -b some-test
      - name: Add commit
        run: git commit --allow-empty -m "empty commit to create PR to start discussion"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: toor1245/cpu-features-dotnet-storage
          github_token: ${{ secrets.TOKEN }}
          branch: some-test
 
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner: 'toor1245',
              repo: 'cpu_features.NET',
              head: 'nuget',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
  
      # alt: https://github.com/marketplace/actions/github-pull-request-action
      # alt: https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.TOKEN}}
          script: |
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner: 'toor1245',
              repo: 'cpu-features-dotnet-storage',
              head: 'toor1245:some-test',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
  