name: Create Nuget Package

on:
  workflow_dispatch:

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: toor1245/cpu-features-dotnet-storage

      # alt: https://github.com/marketplace/actions/github-pull-request-action
      # alt: https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_allow_empty: true
          token: ${{secrets.TOKEN}}
