name: Create Nuget Package

on:
  workflow_dispatch:

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: toor1245/cpu-features-dotnet-storage

      - name: Make some changes
        run: echo "some text" >> test.txt

      # alt: https://github.com/marketplace/actions/github-pull-request-action
      # alt: https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          committer: GitHub Actions Bot <>
          token: ${{secrets.TOKEN}}
