name: .NET tests win.x86-64

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  # Building using the github runner environement directly.
  msvc-x86:
    runs-on:  windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure
        run: cmake -S. -Bcmake-build-release -G "Visual Studio 16 2019" -DCMAKE_CONFIGURATION_TYPES=Release
      - name: Build
        run: cmake --build cmake-build-release --config Release --target ALL_BUILD -- /maxcpucount

      - name: Setup .NET 5.0 @ Latest
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Create build
        run: dotnet build "src/CpuFeaturesDotNet" -c Release --force

      - name: Run Unit Tests
        run: dotnet test "tests" -c Release
